version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: canoypa
      name: homebrew-test-tap
      token: "{{ .Env.RELEASE_TOKEN }}"
    folder: Formula
    homepage: 'https://github.com/canoypa/test-brew-tap'
